In [12]:
import numpy as np


In [13]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)


[1 2 3 4 5]
[5 4 3 2 1]


In [14]:
type(a)

numpy.ndarray

In [15]:
print(a+b)
print(a*b)

[6 6 6 6 6]
[5 8 9 8 5]


[                  ]  1d array
[[]        []]]

In [16]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [17]:
print(x.shape)

(2, 2)


In [18]:
print(a.ndim)

1


In [19]:
print(x.dtype)

int64


In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(2,21)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [22]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
np.random.randint(10,40, size=(3,5))

array([[11, 21, 35, 22, 38],
       [38, 13, 30, 39, 32],
       [37, 20, 35, 36, 19]], dtype=int32)

In [24]:
x = np.array([[7,2,3],
              [2,5,2],
              [3,5,1]])
y = np.array([[1,8,3],[3,7,2],[2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [ ]:
print(x*y)    #matrix multip

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [ ]:
print(x@y)   #matrix multip

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [ ]:
print(x.dot(y)) #matrix multip

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [ ]:
x.prod() #product of all element

np.int64(12600)

In [29]:
x.sum()

np.int64(30)

In [30]:
x.mean()

np.float64(3.3333333333333335)

In [31]:
x.mean(axis=0)

array([4., 4., 2.])

In [32]:
x.mean(axis=1)

array([4., 3., 3.])

In [ ]:
print(x.var())     # varianve 
print(x.std())     # standard deviation
print(x.min())     # minimum     

3.3333333333333335
1.8257418583505538
1


In [37]:
z = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(z, 25))
print(np.percentile(z, 50))
print(np.percentile(z, 75))

3.0
5.0
7.0


In [38]:
arr = np.array([[16,44,46,49],[10,22,41,35],[11,35,20,12],[46,33,41,36]])
print(arr)

[[16 44 46 49]
 [10 22 41 35]
 [11 35 20 12]
 [46 33 41 36]]


In [40]:
print('8x2')
print(arr.reshape(8,2))

8x2
[[16 44]
 [46 49]
 [10 22]
 [41 35]
 [11 35]
 [20 12]
 [46 33]
 [41 36]]


In [41]:
print('2x8')
print(arr.reshape(2,8))

2x8
[[16 44 46 49 10 22 41 35]
 [11 35 20 12 46 33 41 36]]
